/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include <rtthread.h>
#include "GUI.h"
#include <board.h>

#include "DIALOG.h"

//////////////////////////////////////////////////////////
//TOUCH任务
//设置任务优先级
#define TOUCH_TASK_PRIO				  15
//任务堆栈大小
#define TOUCH_STK_SIZE				  216

//EMWINDEMO任务
//设置任务优先级
#define EMWINDEMO_TASK_PRIO			18
//任务堆栈大小
#define EMWINDEMO_STK_SIZE			2048
//////////////////////////////////////////////////////////

#define ID_FRAMEWIN_0 (GUI_ID_USER + 0x00)
#define ID_BUTTON_0 (GUI_ID_USER + 0x01)
#define ID_BUTTON_1 (GUI_ID_USER + 0x02)

//对话框资源表
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] =
{
    { FRAMEWIN_CreateIndirect, "Framewin", ID_FRAMEWIN_0, 0, 0, 800, 480, FRAMEWIN_CF_MOVEABLE, 0x64, 0 },
    { BUTTON_CreateIndirect, "Button", ID_BUTTON_0, 300, 122, 150, 50, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "Button", ID_BUTTON_1, 300, 251, 150, 50, 0, 0x0, 0 },
};

//对话框回调函数
static void _cbDialog(WM_MESSAGE * pMsg)
{
    WM_HWIN hItem;
    int     NCode;
    int     Id;

    switch (pMsg->MsgId)
    {
        case WM_INIT_DIALOG:
            //初始化对话框
            hItem = pMsg->hWin;
            FRAMEWIN_SetTitleHeight(hItem, 30);
            FRAMEWIN_SetText(hItem, "RB_RT-Thread STemwin demo");
            FRAMEWIN_SetFont(hItem, GUI_FONT_24_ASCII);
            FRAMEWIN_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
            FRAMEWIN_SetTextColor(hItem, 0x0000FFFF);

            //初始化BUTTON0
            hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
            BUTTON_SetFont(hItem, GUI_FONT_24_ASCII);
            BUTTON_SetText(hItem, "LED1");

            //初始化BUTTON1
            hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
            BUTTON_SetText(hItem, "BEEP");
            BUTTON_SetFont(hItem, GUI_FONT_24_ASCII);
            break;

        case WM_NOTIFY_PARENT:
            Id    = WM_GetId(pMsg->hWinSrc);
            NCode = pMsg->Data.v;

            switch(Id)
            {
                case ID_BUTTON_0: //BUTTON_0的通知代码，控制LED1
                    switch(NCode)
                    {
                        case WM_NOTIFICATION_CLICKED:
                            break;

                        case WM_NOTIFICATION_RELEASED: //按钮被按下并释放
                            rt_kprintf("led on\n");
                            break;
                    }

                    break;

                case ID_BUTTON_1: //BUTTON_1的通知代码，控制BEEP
                    switch(NCode)
                    {
                        case WM_NOTIFICATION_CLICKED:
                            break;

                        case WM_NOTIFICATION_RELEASED:
                            rt_kprintf("beep on\n");
                            //LED1=~LED1;
                            break;
                    }

                    break;
            }

            break;

        default:
            WM_DefaultProc(pMsg);
            break;
    }
}

//创建一个对话框
WM_HWIN CreateFramewin(void)
{
    WM_HWIN hWin;
    //非阻塞式对话框
    hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
    return hWin;
}

//BUTTON按钮上显示位图
void Buttonbmp_Demo(void)
{
    WM_HWIN hWin;
    hWin = CreateFramewin();

    while(1)
    {
        GUI_Delay(10);
    }
}

static void Sys_CRC_Init(void)
{
    CRC_HandleTypeDef CrcHandle;
    CrcHandle.State = HAL_CRC_STATE_RESET;
    CrcHandle.Instance = CRC;
    HAL_CRC_Init(&CrcHandle);
}

//显示任务
static void STemwin_thread(void *param)
{
    Sys_CRC_Init();
    WM_SetCreateFlags(WM_CF_MEMDEV); 	//启动所有窗口的存储设备
    GUI_Init();
    //
    GUI_CURSOR_Show();
    //更换皮肤
    BUTTON_SetDefaultSkin(BUTTON_SKIN_FLEX);
    CHECKBOX_SetDefaultSkin(CHECKBOX_SKIN_FLEX);
    DROPDOWN_SetDefaultSkin(DROPDOWN_SKIN_FLEX);
    FRAMEWIN_SetDefaultSkin(FRAMEWIN_SKIN_FLEX);
    HEADER_SetDefaultSkin(HEADER_SKIN_FLEX);
    MENU_SetDefaultSkin(MENU_SKIN_FLEX);
    MULTIPAGE_SetDefaultSkin(MULTIPAGE_SKIN_FLEX);
    PROGBAR_SetDefaultSkin(PROGBAR_SKIN_FLEX);
    RADIO_SetDefaultSkin(RADIO_SKIN_FLEX);
    SCROLLBAR_SetDefaultSkin(SCROLLBAR_SKIN_FLEX);
    SLIDER_SetDefaultSkin(SLIDER_SKIN_FLEX);
    SPINBOX_SetDefaultSkin(SPINBOX_SKIN_FLEX);

    while (1)
    {
        Buttonbmp_Demo();
    }
}

//触摸任务
static void touch_thread(void *param)
{
    while(1)
    {
        GUI_TOUCH_Exec();
        rt_thread_mdelay(5);
    }
}

static int Gui_emwin_init(void)
{
    rt_thread_t tid;
    tid = rt_thread_create("emwin",
                           STemwin_thread, RT_NULL,
                           EMWINDEMO_STK_SIZE,
                           EMWINDEMO_TASK_PRIO, 10);

    if (tid != RT_NULL)
        rt_thread_startup(tid);

    return RT_EOK;
}
INIT_APP_EXPORT(Gui_emwin_init);

static int Gui_touch_init(void)
{
    rt_thread_t btn_tid;
    btn_tid = rt_thread_create("touch",
                               touch_thread, RT_NULL,
                               TOUCH_STK_SIZE,
                               TOUCH_TASK_PRIO, 10);

    if (btn_tid != RT_NULL)
        rt_thread_startup(btn_tid);

    return RT_EOK;
}
INIT_APP_EXPORT(Gui_touch_init);
/*************************** End of file ****************************/
