/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END
#include <rtthread.h>
#include <board.h>

//////////////////////////////////////////////////////////
//EMWINDEMO任务
//设置任务优先级
#define EMWINDEMO_TASK_PRIO			18
//任务堆栈大小
#define EMWINDEMO_STK_SIZE			2048
//////////////////////////////////////////////////////////


//显示任务
static void STemwin_thread(void *param)
{

    while (1)
    {
        rt_thread_mdelay(500);
    }
}


static int Gui_emwin_init(void)
{
    rt_thread_t tid;
    tid = rt_thread_create("lvgl",
                           STemwin_thread, RT_NULL,
                           EMWINDEMO_STK_SIZE,
                           EMWINDEMO_TASK_PRIO, 10);

    if (tid != RT_NULL)
        rt_thread_startup(tid);

    return RT_EOK;
}
//INIT_APP_EXPORT(Gui_emwin_init);


/*************************** End of file ****************************/
