Import('rtconfig')
from building import *

cwd = GetCurrentDir()
CPPPATH = [cwd]
src = Glob('TOUCH/*.c')

group = DefineGroup('Hardware', src, depend = ['ART_PI_USING_HARDWARE'], CPPPATH = CPPPATH)

Return('group')
